repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-yaml
  - id: debug-statements
  - id: check-ast

- repo: https://github.com/psf/black
  rev: 23.12.1
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/PyCQA/flake8/
  rev: 7.0.0
  hooks:
  - id: flake8
    additional_dependencies: [flake8-docstrings]

- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]
    #    additional_dependencies: [toml]

- repo: https://github.com/PyCQA/doc8
  rev: v1.1.1
  hooks:
  - id: doc8

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
  hooks:
  - id: mypy
    args: [--strict, --pretty, --show-error-codes]
    additional_dependencies:
      - "types-PyYAML==6.0.12.20240311"
      - "pytest-stub==1.1.0"
      - "types-paho-mqtt==1.6.0.20240106"
      - "homeassistant-stubs==2024.3.0"
      - "Hydro_Quebec_API_Wrapper==3.1.3"
      - "mqtt-hass-base==4.2.6"
      - "aioresponses==0.7.6"
      - "types-python-dateutil==2.9.0.20240315"
      - "types-pytz==2023.4.0.20240130"
      - "pkce==1.0.3"
      - "aiomqtt==2.0.1"
