SENSORS = {
    # Account
    "balance": {
        "name": "Balance",
        "data_source": "account.balance",
        "device_class": "monetary",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:currency-usd",
        "state_class": "measurement",
        "unit": "$",
        "sub_mqtt_topic": "account/state",
    },
    # Contract
    "current_period_current_days": {
        # TODO find a better name
        "name": "Current period current days",
        "data_source": "contract.cp_current_days",
        "device_class": None,
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:calendar-start",
        "state_class": "measurement",
        "unit": "days",
        "sub_mqtt_topic": "contract/state",
    },
    "current_period_duration": {
        "name": "Current period duration",
        "data_source": "contract.cp_duration",
        "device_class": None,
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:calendar-expand-horizontal",
        "state_class": "measurement",
        "unit": "days",
        "sub_mqtt_topic": "contract/state",
    },
    "current_period_current_bill": {
        # TODO find a better name
        "name": "Current period current bill",
        "data_source": "contract.cp_current_bill",
        "device_class": "monetary",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:currency-usd",
        "state_class": "measurement",
        "unit": "$",
        "sub_mqtt_topic": "contract/state",
    },
    "current_period_projected_bill": {
        "name": "Current period projected bill",
        "data_source": "contract.cp_projected_bill",
        "device_class": "monetary",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:currency-usd",
        "state_class": "measurement",
        "unit": "$",
        "sub_mqtt_topic": "contract/state",
    },
    "current_period_daily_bill_mean": {
        "name": "Current period daily bill mean",
        "data_source": "contract.cp_daily_bill_mean",
        "device_class": "monetary",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:currency-usd",
        "state_class": "measurement",
        "unit": "$",
        "sub_mqtt_topic": "contract/state",
    },
    "current_period_daily_consumption_mean": {
        "name": "Current period daily consumption mean",
        "data_source": "contract.cp_daily_consumption_mean",
        "device_class": "energy",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:home-lightning-bolt",
        "state_class": "measurement",
        "unit": "kWh",
        "sub_mqtt_topic": "contract/state",
    },
    "current_period_total_consumption": {
        "name": "Current period total consumption",
        "data_source": "contract.cp_total_consumption",
        "device_class": "energy",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:home-lightning-bolt",
        "state_class": "measurement",
        "unit": "kWh",
        "sub_mqtt_topic": "contract/state",
    },
    "current_period_projected_total_consumption": {
        "name": "Current period projected total consumption",
        "data_source": "contract.cp_projected_total_consumption",
        "device_class": "energy",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:home-lightning-bolt",
        "state_class": "measurement",
        "unit": "kWh",
        "sub_mqtt_topic": "contract/state",
    },
    "current_period_projected_total_consumption": {
        "name": "Current period projected total consumption",
        "data_source": "contract.cp_projected_total_consumption",
        "device_class": "energy",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:home-lightning-bolt",
        "state_class": "measurement",
        "unit": "kWh",
        "sub_mqtt_topic": "contract/state",
    },
    "current_period_higher_price_consumption": {
        "name": "Current period higher price consumption",
        "data_source": "contract.cp_higher_price_consumption",
        "device_class": "energy",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:home-lightning-bolt",
        "state_class": "measurement",
        "unit": "kWh",
        "sub_mqtt_topic": "contract/state",
    },
    "current_period_lower_price_consumption": {
        "name": "Current period lower price consumption",
        "data_source": "contract.cp_lower_price_consumption",
        "device_class": "energy",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:home-lightning-bolt-outline",
        "state_class": "measurement",
        "unit": "kWh",
        "sub_mqtt_topic": "contract/state",
    },
    "current_period_average_temperature": {
        "name": "Current period average temperature",
        "data_source": "contract.cp_average_temperature",
        "device_class": "temperature",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:thermometer",
        "state_class": "measurement",
        "unit": "°C",
        "sub_mqtt_topic": "contract/state",
    },
    "current_period_kwh_cost_mean": {
        "name": "Current period kwh cost mean",
        "data_source": "contract.cp_kwh_cost_mean",
        "device_class": "monetary",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:currency-usd",
        "state_class": "measurement",
        "unit": "$",
        "sub_mqtt_topic": "contract/state",
    },
    "current_period_rate": {
        "name": "Current period rate",
        "data_source": "contract.cp_rate",
        "device_class": None,
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:playlist-check",
        "state_class": None,
        "unit": None,
        "sub_mqtt_topic": "contract/state",
    },
    # Winter credits
    "wc_cumulated_credit": {
        "name": "Cumulated Winter Credit",
        "data_source": "contract.winter_credit.value_cumulated_credit",
        "device_class": "monetary",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:currency-usd",
        "state_class": "measurement",
        "unit": "$",
        "sub_mqtt_topic": "wintercredits/state",
    },
    "wc_next_anchor_start": {
        "name": "Next Anchor Period Start",
        "data_source": "contract.winter_credit.value_next_periods_anchor_start_iso",
        "device_class": "timestamp",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:clock-start",
        "sub_mqtt_topic": "wintercredits/next/anchor",
    },
    "wc_next_anchor_end": {
        "name": "Next Anchor Period End",
        "data_source": "contract.winter_credit.value_next_periods_anchor_end_iso",
        "device_class": "timestamp",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:clock-end",
        "sub_mqtt_topic": "wintercredits/next/anchor",
    },
    "wc_next_peak_start": {
        "name": "Next Peak Period Start",
        "data_source": "contract.winter_credit.value_next_periods_peak_start_iso",
        "device_class": "timestamp",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:clock-start",
        "sub_mqtt_topic": "wintercredits/next/peak",
    },
    "wc_next_peak_end": {
        "name": "Next Peak Period End",
        "data_source": "contract.winter_credit.value_next_periods_peak_end_iso",
        "device_class": "timestamp",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:clock-end",
        "sub_mqtt_topic": "wintercredits/next/peak",
    },
    "wc_next_critical_event_start": {
        "name": "Next Critical Event Start",
        "data_source": "contract.winter_credit.value_next_start_iso",
        "device_class": "timestamp",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:clock-start",
        "sub_mqtt_topic": "wintercredits/next/event",
    },
    "wc_next_critical_event_end": {
        "name": "Next Critical Event End",
        "data_source": "contract.winter_credit.value_next_end_iso",
        "device_class": "timestamp",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:clock-end",
        "sub_mqtt_topic": "wintercredits/next/event",
    },
}
BINARY_SENSORS = {
    # Contracts
    "current_period_epp_enabled": {
        "name": "Current period epp enabled",
        "data_source": "contract.cp_epp_enabled",
        "device_class": None,
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:code-equal",
        "sub_mqtt_topic": "contract/state",
    },
    # Winter credits
    "wc_critical": {
        "name": "Critical",
        "data_source": "contract.winter_credit.value_state_critical",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:flash-alert",
        "sub_mqtt_topic": "wintercredits/state",
    },
    "wc_event_in_progress": {
        "name": "Event In Progress",
        "data_source": "contract.winter_credit.value_state_event_in_progress",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:flash-alert",
        "sub_mqtt_topic": "wintercredits/state",
    },
    "wc_pre_heat": {
        "name": "Pre-heat In Progress",
        "data_source": "contract.winter_credit.value_state_pre_heat",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:flash-alert",
        "sub_mqtt_topic": "wintercredits/state",
    },
    "wc_next_anchor_critical": {
        "name": "Next Anchor Period Critical",
        "data_source": "contract.winter_credit.value_next_periods_anchor_critical",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:flash-alert",
        "sub_mqtt_topic": "wintercredits/state",
    },
    "wc_next_peak_critical": {
        "name": "Next Peak Period Critical",
        "data_source": "contract.winter_credit.value_next_periods_peak_critical",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:flash-alert",
        "sub_mqtt_topic": "wintercredits/state",
    },
    "wc_upcoming_critical_event": {
        "name": "Upcoming Critical Event",
        "data_source": "contract.winter_credit.value_state_upcoming_event",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:flash-alert",
        "sub_mqtt_topic": "wintercredits/state",
    },
    "wc_upcoming_event_today_morning": {
        "name": "Upcoming event today morning",
        "data_source": "contract.winter_credit.value_state_morning_event_today",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:message-flash",
        "sub_mqtt_topic": "wintercredits/state",
    },
    "wc_upcoming_event_today_evening": {
        "name": "Upcoming event today evening",
        "data_source": "contract.winter_credit.value_state_evening_event_today",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:message-flash",
        "sub_mqtt_topic": "wintercredits/state",
    },
    "wc_upcoming_event_tomorrow_morning": {
        "name": "Upcoming event tomorrow morning",
        "data_source": "contract.winter_credit.value_state_morning_event_tomorrow",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:message-flash",
        "sub_mqtt_topic": "wintercredits/state",
    },
    "wc_upcoming_event_tomorrow_evening": {
        "name": "Upcoming event tomorrow evening",
        "data_source": "contract.winter_credit.value_state_evening_event_tomorrow",
        "expire_after": 0,
        "force_update": False,
        "icon": "mdi:message-flash",
        "sub_mqtt_topic": "wintercredits/state",
    }
}
